config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :directors
  resources :genres
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
  belongs_to :genre
  has_many :movies, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movies, dependent: :destroy
  has_many :directors, dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director
  belongs_to :genre

  enum status: {draft: 0, published: 1}
  enum release: {unrelease: 0, released: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: %i[ show edit update destroy ]

  # GET /directors or /directors.json
  def index
    @directors = Director.all.order("name")
  end

  # GET /directors/1 or /directors/1.json
  def show
    @movies = @director.movies
  end

  # GET /directors/new
  def new
    @director = Director.new
  end

  # GET /directors/1/edit
  def edit
  end

  # POST /directors or /directors.json
  def create
    @director = Director.new(director_params)

    respond_to do |format|
      if @director.save
        format.html { redirect_to directors_url, notice: "Diretor cadastrado com sucesso!" }
        format.json { render :show, status: :created, location: @director }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directors/1 or /directors/1.json
  def update
    respond_to do |format|
      if @director.update(director_params)
        format.html { redirect_to directors_url, notice: "Diretor alterado com sucesso!" }
        format.json { render :show, status: :ok, location: @director }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1 or /directors/1.json
  def destroy
    @director.destroy

    respond_to do |format|
      format.html { redirect_to directors_url, notice: "Diretor excluído com sucesso!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_director
      @director = Director.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def director_params
      params.require(:director).permit(:name, :nationality, :date_birth, :genre_id)
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[ show edit update destroy ]

  # GET /genres or /genres.json
  def index
    @genres = Genre.all.order("name")
  end

  # GET /genres/1 or /genres/1.json
  def show
    @movies = @genre.movies
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres or /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to genres_path, notice: "Gênero cadastrado com sucesso!" }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1 or /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to genres_path, notice: "Gênero alterado com sucesso!" }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1 or /genres/1.json
  def destroy
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to genres_url, notice: "Gênero excuído com sucesso!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.published.order("title")
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    # @movie.status = :draft if params[:movie][:status] == "1"
    @movie = Movie.new(movie_params)
    
    puts movie_params
    respond_to do |format|
      if @movie.save
         format.html { redirect_to movies_url, notice: "Filme cadastrado com sucesso!" }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
   end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|

      if @movie.update(movie_params)
        format.html { redirect_to movies_url, notice: "Filme alterado com sucesso!" }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Filme excluído com sucesso!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :release_year, :synopsis, :country, :duration, :director_id, :genre_id, :status, :release)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/directors/_director.html.erb
<div id="<%= dom_id director %>">
  <p>
    <strong>Name:</strong>
    <%= director.name %>
  </p>

  <p>
    <strong>Nationality:</strong>
    <%= director.nationality %>
  </p>

  <p>
    <strong>Date birth:</strong>
    <%= director.date_birth %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= director.genre_id %>
  </p>

</div>

app/views/directors/_form.html.erb
<%= form_with(model: director) do |form| %>
  <% if director.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(director.errors.count, "error") %> prohibited this director from being saved:</h2>

      <ul>
        <% director.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-floating mb-3">
    <%= form.text_field :name, class: 'form-control mb-2', placeholder: "Nome do diretor", required: true %>
    <%= form.label :name, for: "floatingInput" %>
  </div>

  <div class="form-floating mb-3">
    <%= form.text_field :nationality, class: 'form-control mb-2', placeholder: "Nacionalidade" , required: true %>
    <%= form.label :nationality, for: "floatingInput" %>
  </div>

  <div class="form-floating mb-3">
    <%= form.date_field :date_birth, class: 'form-control  mb-3', required: true%>
    <%= form.label :date_birth, for: "floatingInput" %>
  </div>

  <div class="form-floating mb-3">
    <%= form.collection_select(:genre_id, Genre.order(:name), :id, :name , { prompt: 'Selecione' }, { class: 'form-control mb-2' , required: true}) %>
    <%= form.label "Escolha o gênero favorito do diretor", for: "floatingInput" %>
  </div>

    <div class="d-flex justify-content-center">
      <%= form.submit 'Salvar', class: 'btn btn-secondary  mt-2' %>
      <%= link_to "Voltar", :back, class: "btn btn-outline-secondary mt-2 ms-2" %>
    </div>

<% end %>

app/views/directors/edit.html.erb
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <h2 class="text-center">Diretor</h2>
</div>
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <%= render "form", director: @director %>
  <div class="mt-4">
    <%= link_to "Show this director", @director %> |
    <%= link_to "Back to directors", directors_path %>
  </div>
</div>

app/views/directors/index.html.erb
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <h2 class="text-center">Diretores</h2>
</div>
<div class="container text-center text-success"><%= notice %></div><br>
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <%= link_to "Novo Diretor", new_director_path, class: "btn btn-outline-secondary" %>
  <% if @directors.any? %>
    <div id="directors">
      <dl class="row p-3 text-muted">
        <% @directors.each do |director| %>
          <dt class="col-sm-6"><%= link_to director.name, director_path(director)  %></dt>
          <dd class="col-sm-auto"><%= link_to "Editar", edit_director_path(director), class: "btn btn-outline-secondary" %></dd>
          <dd class="col-sm-auto"><%= button_to "Excluir", director_path(director), class: "btn btn-outline-secondary",
          form: { data: { turbo_confirm: "Tem certeza que deseja excluir?" } }, method: :delete %></dd>
        <% end %>
      </dl>
    </div>
  <% end %>
</div>
    

app/views/directors/new.html.erb
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <h2 class="text-center">Novo Diretor</h2>
</div>
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <%= render "form", director: @director %>
  <div class="mt-4">
    <%= link_to "Back to directors", directors_path %>
  </div>
</div>

app/views/directors/show.html.erb
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <h2 class="text-center">Filmes do diretor <%= @director.name %></h2>
</div>
<div class="container text-center text-success"><%= notice %></div>
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <% if @movies.any? %>
    <div id="movies">
      <dl class="row p-3 text-muted">
        <% @movies.each do |movie| %>
          <dt class="col-sm-12">
            <%= movie.title %> - <%= movie.release_year %>
          </dt>
        <% end %>
      </dl>
    </div>
  <% end %>  
  <div class="mt-4">
  <%= link_to "Back to genres", directors_path %>
</div>
</div>

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |form| %>
    <% if genre.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

        <ul>
          <% genre.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-floating mb-3">
      <%= form.text_field :name, class: 'form-control mb-2', placeholder: "Nome de gênero", required: true %>
      <%= form.label :name, for: "floatingInput" %>
    </div>
    <div class="d-flex justify-content-center">
      <%= form.submit 'Salvar', class: 'btn btn-secondary  mt-2' %>
      <%= link_to "Voltar", :back, class: "btn btn-outline-secondary mt-2 ms-2" %>
    </div>
<% end %>

app/views/genres/_genre.html.erb
<div id="<%= dom_id genre %>">
  <p>
    <strong>Name:</strong>
    <%= genre.name %>
  </p>

</div>

app/views/genres/edit.html.erb
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <h2 class="text-center">Gênero</h2>
</div>
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <%= render "form", genre: @genre %>
  <div class="mt-4">
    <%= link_to "Show this genre", @genre %> |
    <%= link_to "Back to genres", genres_path %>
  </div>
</div>

app/views/genres/index.html.erb
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <h2 class="text-center">Gêneros</h2>
</div>
<div class="container text-center text-success"><%= notice %></div><br>
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <%= link_to "Novo Gênero", new_genre_path, class: "btn btn-outline-secondary" %>
  <% if @genres.any? %>
    <div id="genres">
      <dl class="row p-3 text-muted">
        <% @genres.each do |genre| %>
          <dt class="col-sm-6"><%= link_to genre.name , genre_path(genre) %></dt>
          <dd class="col-sm-auto"><%= link_to "Editar", edit_genre_path(genre), class: "btn btn-outline-secondary" %></dd>
          <dd class="col-sm-auto"><%= button_to "Excluir", genre_path(genre), class: "btn btn-outline-secondary",
          form: { data: { turbo_confirm: "Tem certeza que deseja excluir?" } }, method: :delete %></dd>
        <% end %>
      </dl>
    </div>
  <% end %>
</div>

app/views/genres/new.html.erb
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <h2 class="text-center">Novo Gênero</h2>
</div>
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <%= render "form", genre: @genre %>
  <div class="mt-4">
    <%= link_to "Back to genres", genres_path %>
  </div>
</div>

app/views/genres/show.html.erb
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <h2 class="text-center">Filmes do gênero <%= @genre.name %></h2>
</div>
<div class="container text-center text-success"><%= notice %></div><br>
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <% if @movies.any? %>
    <div id="movies">
      <dl class="row p-3 text-muted">
        <% @movies.each do |movie| %>
          <dt class="col-sm-12"><%= movie.title %> - <%= movie.release_year %></dt>
        <% end %>
      </dl>
    </div>
  <% end %>  
  <div class="mt-4">
  <%= link_to "Back to genres", genres_path %>
</div>
</div>

app/views/homes/index.html.erb
<h1>CineApp</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/homes/index_outra.html.erb
<div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Bootstrap Sidebar</h3>
            </div>

            <ul class="list-unstyled components">
                <p>Dummy Heading</p>
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="#">Home 1</a>
                        </li>
                        <li>
                            <a href="#">Home 2</a>
                        </li>
                        <li>
                            <a href="#">Home 3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">Page 1</a>
                        </li>
                        <li>
                            <a href="#">Page 2</a>
                        </li>
                        <li>
                            <a href="#">Page 3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">Portfolio</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>

            <ul class="list-unstyled CTAs">
                <li>
                    <a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a>
                </li>
                <li>
                    <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a>
                </li>
            </ul>
        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span>Toggle Sidebar</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            <h2>Collapsible Sidebar Using Bootstrap 4</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <div class="line"></div>

            <h2>Lorem Ipsum Dolor</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <div class="line"></div>

            <h2>Lorem Ipsum Dolor</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <div class="line"></div>

            <h3>Lorem Ipsum Dolor</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cineapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <div class="row">
              <div class="col nav-item">
                <%= link_to "Home", root_path %>
              </div>
              <div class="col nav-item">
                <%= link_to "Gêneros", genres_path %>
              </div>
              <div class="col nav-item">
                <%= link_to "Diretores", directors_path %>
              </div>
              <div class="col nav-item">
                <%= link_to "Filmes", movies_path %>
              </div>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Home", root_path %>
        <%= link_to "Gêneros", movies_path %>
        <%= link_to "Diretores", movies_path %>
        <%= link_to "Filmes", movies_path %>
      </div>
    </div>
  </div>
</nav>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-floating mb-3">
    <%= form.text_field :title, class: 'form-control mb-2', placeholder: "Nome do filme", required: true %>
    <%= form.label :title, for: "floatingInput" %>
  </div>

  <div class="form-floating mb-3">
    <%= form.number_field :release_year, class: 'form-control mb-2', placeholder: "Nome do filme", required: true  %>
    <%= form.label :release_year, for: "floatingInput" %>
  </div>

  <div class="form-floating mb-3">
      <%= form.text_area :synopsis, class: 'form-control mb-2', placeholder: "Nome do filme", required: true  %>
      <%= form.label :synopsis, for: "floatingInput" %>
  </div>

  <div class="form-floating mb-3">
    <%= form.text_field :country, class: 'form-control mb-2', placeholder: "Nome do filme", required: true  %>
    <%= form.label :country, for: "floatingInput" %>
  </div>

  <div class="form-floating mb-3">
    <%= form.number_field :duration, class: 'form-control mb-2', placeholder: "Nome do filme", required: true  %>
    <%= form.label :duration, for: "floatingInput" %>
  </div>

  <div class="form-floating mb-3">
    <%= form.collection_select(:director_id, Director.order(:name), :id, :name , { prompt: 'Selecione' }, { class: 'form-control mb-2' , required: true}) %>
    <%= form.label :director_id, for: "floatingInput" %>
  </div>

  <div class="form-floating mb-3">
    <%= form.collection_select(:genre_id, Genre.order(:name), :id, :name , { prompt: 'Selecione' }, { class: 'form-control mb-2' , required: true}) %>
    <%= form.label :genre_id, for: "floatingInput" %>
  </div>

  <div class="form-control mb-3">
    <%= form.label :status %>
    <%= form.select :status, options_for_select(Movie.statuses.keys.map { |status| [status.titleize, status] }, :selected => form.object.status), {prompt: "Escolher" }, { class: "form-control  mb-2 border-0 border-bottom", 'data-style': 'form-control'  , required: true}  %>
    
  </div>

  <div class="form-control mb-3">
    <%= form.label :release %>
    <%= form.select :release, options_for_select(Movie.releases.keys.map { |release| [release.humanize, release] }, :selected => form.object.release) , {prompt: "Escolher" }, { class: "form-control  mb-2 border-0 border-bottom", 'data-style': 'form-control'  , required: true} %>
  </div>

  <div class="d-flex justify-content-center">
    <%= form.submit 'Salvar', class: 'btn btn-secondary  mt-2' %>
    <%= link_to "Voltar", :back, class: "btn btn-outline-secondary mt-2 ms-2" %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <strong>Title:</strong>
    <%= movie.title %>
  </p>

  <p>
    <strong>Release year:</strong>
    <%= movie.release_year %>
  </p>

  <p>
    <strong>Synopsis:</strong>
    <%= movie.synopsis %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= movie.country %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= movie.duration %>
  </p>

  <p>
    <strong>Director:</strong>
    <%= movie.director_id %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= movie.genre_id %>
  </p>

</div>

app/views/movies/edit.html.erb
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <h2 class="text-center">Filme</h2>
</div>
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <%= render "form",  movie: @movie %>
  <div class="mt-4">
    <%= link_to "Show this movie", @movie %> |
    <%= link_to "Back to movies", movies_path %>
  </div>
</div>

app/views/movies/new.html.erb
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <h2 class="text-center">Novo Filme</h2>
</div>
<div class="container shadow p-2 mb-4 bg-body-tertiary rounded">
  <%= render "form", movie: @movie  %>
  <div class="mt-4">
    <%= link_to "Back to movies", movies_path %>
  </div>
</div>